services:
  - type: web
    name: reelbrief-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      flask db upgrade
      gunicorn -w 4 -b 0.0.0.0:$PORT run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production