"""Update escrow model fields

Revision ID: 0415abb4712a
Revises: 893da7a97be1
Create Date: 2025-11-03 13:11:26.847756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0415abb4712a'
down_revision = '893da7a97be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escrow_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('escrow_transactions_invoice_number_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('escrow_transactions_project_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('escrow_transactions_admin_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('escrow_transactions_client_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('escrow_transactions_freelancer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'invoices', ['invoice_id'], ['id'])
        batch_op.drop_column('payment_method')
        batch_op.drop_column('admin_id')
        batch_op.drop_column('client_id')
        batch_op.drop_column('currency')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('invoice_url')
        batch_op.drop_column('freelancer_id')
        batch_op.drop_column('notes')
        batch_op.drop_column('held_at')
        batch_op.drop_column('refunded_at')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('invoices_escrow_id_fkey'), type_='foreignkey')
        batch_op.drop_column('escrow_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escrow_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('invoices_escrow_id_fkey'), 'escrow_transactions', ['escrow_id'], ['id'])

    with op.batch_alter_table('escrow_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refunded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('held_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('freelancer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('invoice_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('escrow_transactions_freelancer_id_fkey'), 'users', ['freelancer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('escrow_transactions_client_id_fkey'), 'users', ['client_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('escrow_transactions_admin_id_fkey'), 'users', ['admin_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('escrow_transactions_project_id_key'), ['project_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('escrow_transactions_invoice_number_key'), ['invoice_number'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###
