"""Add invoice and payment fields to escrow

Revision ID: 3774f01564cd
Revises: 0415abb4712a
Create Date: 2025-11-03 13:25:27.917232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3774f01564cd'
down_revision = '0415abb4712a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escrow_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('invoice_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refunded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escrow_transactions', schema=None) as batch_op:
        batch_op.drop_column('refunded_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('invoice_url')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
