"""Fix skills relationship formatting and back_populates

Revision ID: 7f8c4b03abd6
Revises: 345b26a91670
Create Date: 2025-10-30 09:09:31.342981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f8c4b03abd6'
down_revision = '345b26a91670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('freelancer_skills', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_freelancer_skill'), type_='unique')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('budget',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('freelancer_skills', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_freelancer_skill'), ['freelancer_id', 'skill_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
